name: Update Xoilac M3U

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & Playwright browsers
        run: |
          pip install requests beautifulsoup4 playwright
          playwright install --with-deps chromium

      - name: Run script
        run: python main.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update M3U with live tokens [skip ci]"
          file_patterns: xoilac_live.m3u
